server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: product_api
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
