server:
  port: 8000
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.200.33/gmall_product?useSSL=false
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
#  cloud:
#    nacos:
#      server-addr: 192.168.200.33:8848
#      config:
#        shared-configs: #共享配置,再nacos中
#          - dataId: uploadFile.yaml


